name: Build MyQode
on: push
jobs:

  build-ios:
    runs-on: macos-10.14
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'

      - name: Setup custom environment variables
        run: |
          echo ::set-env name=BUILD_NUMBER::"MyQode-MacOS-`date '+%m%d'`-$GITHUB_RUN_NUMBER"

      - name: MyQode -> Install
        run: |
          yarn install
          brew uninstall --ignore-dependencies perl
          wget https://codeload.github.com/Perl/perl5/tar.gz/v5.18.4
          npm install tar -g
          tar -xvf v5.18.4.tar.gz
          mv v5.18.4 perl && cd ./perl
          ./Configure -de
          make && make test && make install
        
      - name: MyQode -> Certificate
        env:
          CERTIFICATE_OSX_P12: ${{secrets.CERTIFICATE_OSX_P12}}
          CERTIFICATE_PASSWORD: ${{secrets.CERTIFICATE_PASSWORD}}
        run: |
          export CERTIFICATE_P12=Certificate.p12
          echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12
          export KEYCHAIN=build.keychain
          security create-keychain -p mysecretpassword $KEYCHAIN
          security default-keychain -s $KEYCHAIN
          security unlock-keychain -p mysecretpassword $KEYCHAIN
          security set-keychain-settings -t 3600 -u $KEYCHAIN
          security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword $KEYCHAIN
          rm -rf ./www/remote/arduino/win32
          rm -rf ./www/remote/sources/Python

      - name: MyQode -> Build/release
        run: |
          npx electron-builder

      - name: Upload to Aliyun OSS
        run: |
          curl https://static-hk-robobloq.oss-cn-hongkong.aliyuncs.com/certificate/q-release-mac -o q-release
          7z a -tzip $BUILD_NUMBER.zip .\releases\*.*
          chmod a+x q-release
          q-release upload $BUILD_NUMBER.zip
